export const API_ERROR = {
	EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
	EMAIL_NOT_VERIFIED: "EMAIL_NOT_VERIFIED",
	HTTP_ERROR: "HTTP_ERROR",
	INTERNAL_ERROR: "INTERNAL_ERROR",
	INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
	INVALID_SESSION: "INVALID_SESSION",
	INVALID_TOKEN: "INVALID_TOKEN",
	NOT_FOUND: "NOT_FOUND",
	POST_NOT_FOUND: "POST_NOT_FOUND",
	SESSION_EXPIRED: "SESSION_EXPIRED",
	USER_NOT_FOUND: "USER_NOT_FOUND",
	VALIDATION_ERROR: "VALIDATION_ERROR",
} as const;
